### ISSUE TITLE
Can't connect to Yeelight button YLAI003

### ISSUE THREAD

**Issue by barbudor** [dnandha/miauth#11]
Hello

I'm trying to get the key for this Yeelight button: https://www.aliexpress.com/item/1005001552119268.html
But miauth fails on a connection error

Here are some details:
- Hardware : mini PC x64
- OS : Ubuntu 20.04 LTS
- bluepy : 1.3.0
- miauth : 0.9.6
- Device MAC : b4:60:ed:9b:06:d2

- bluetoothctl / connect / menu gatt / list-attributes
```
[YLKG]# list-attributes
Primary Service (Handle 0x0009)
        /org/bluez/hci0/dev_B4_60_ED_9B_06_D2/service002a
        00000100-0065-6c62-2e74-6f696d2e696d
        Vendor specific
Characteristic (Handle 0xced4)
        /org/bluez/hci0/dev_B4_60_ED_9B_06_D2/service002a/char002d
        00000102-0065-6c62-2e74-6f696d2e696d
        Vendor specific
Descriptor (Handle 0x0015)
        /org/bluez/hci0/dev_B4_60_ED_9B_06_D2/service002a/char002d/desc002f
        00002902-0000-1000-8000-00805f9b34fb
        Client Characteristic Configuration
Characteristic (Handle 0xe4e8)
        /org/bluez/hci0/dev_B4_60_ED_9B_06_D2/service002a/char002b
        00000101-0065-6c62-2e74-6f696d2e696d
        Vendor specific
Primary Service (Handle 0x0920)
        /org/bluez/hci0/dev_B4_60_ED_9B_06_D2/service001b
        0000fe95-0000-1000-8000-00805f9b34fb
        Xiaomi Inc.
Characteristic (Handle 0xfcf4)
        /org/bluez/hci0/dev_B4_60_ED_9B_06_D2/service001b/char0027
        00000018-0000-1000-8000-00805f9b34fb
        Unknown
Descriptor (Handle 0x0015)
        /org/bluez/hci0/dev_B4_60_ED_9B_06_D2/service001b/char0027/desc0029
        00002902-0000-1000-8000-00805f9b34fb
        Client Characteristic Configuration
Characteristic (Handle 0x1478)
        /org/bluez/hci0/dev_B4_60_ED_9B_06_D2/service001b/char0024
        00000017-0000-1000-8000-00805f9b34fb
        AVCTP
Descriptor (Handle 0x0015)
        /org/bluez/hci0/dev_B4_60_ED_9B_06_D2/service001b/char0024/desc0026
        00002902-0000-1000-8000-00805f9b34fb
        Client Characteristic Configuration
Characteristic (Handle 0x3898)
        /org/bluez/hci0/dev_B4_60_ED_9B_06_D2/service001b/char0021
        00000019-0000-1000-8000-00805f9b34fb
        AVDTP
Descriptor (Handle 0x0015)
        /org/bluez/hci0/dev_B4_60_ED_9B_06_D2/service001b/char0021/desc0023
        00002902-0000-1000-8000-00805f9b34fb
        Client Characteristic Configuration
Characteristic (Handle 0x4f88)
        /org/bluez/hci0/dev_B4_60_ED_9B_06_D2/service001b/char001e
        00000010-0000-1000-8000-00805f9b34fb
        UPNP
Descriptor (Handle 0x0015)
        /org/bluez/hci0/dev_B4_60_ED_9B_06_D2/service001b/char001e/desc0020
        00002902-0000-1000-8000-00805f9b34fb
        Client Characteristic Configuration
Characteristic (Handle 0x64a8)
        /org/bluez/hci0/dev_B4_60_ED_9B_06_D2/service001b/char001c
        00000004-0000-1000-8000-00805f9b34fb
        Unknown
Primary Service (Handle 0x0920)
        /org/bluez/hci0/dev_B4_60_ED_9B_06_D2/service0012
        0000180a-0000-1000-8000-00805f9b34fb
        Device Information
Characteristic (Handle 0x73d4)
        /org/bluez/hci0/dev_B4_60_ED_9B_06_D2/service0012/char0019
        00002a26-0000-1000-8000-00805f9b34fb
        Firmware Revision String
Characteristic (Handle 0x73d4)
        /org/bluez/hci0/dev_B4_60_ED_9B_06_D2/service0012/char0017
        00002a27-0000-1000-8000-00805f9b34fb
        Hardware Revision String
Characteristic (Handle 0x73d4)
        /org/bluez/hci0/dev_B4_60_ED_9B_06_D2/service0012/char0015
        00002a24-0000-1000-8000-00805f9b34fb
        Model Number String
Characteristic (Handle 0x73d4)
        /org/bluez/hci0/dev_B4_60_ED_9B_06_D2/service0012/char0013
        00002a29-0000-1000-8000-00805f9b34fb
        Manufacturer Name String
Primary Service (Handle 0x0920)
        /org/bluez/hci0/dev_B4_60_ED_9B_06_D2/service0001
        00001801-0000-1000-8000-00805f9b34fb
        Generic Attribute Profile
Characteristic (Handle 0xb134)
        /org/bluez/hci0/dev_B4_60_ED_9B_06_D2/service0001/char0002
        00002a05-0000-1000-8000-00805f9b34fb
        Service Changed
Descriptor (Handle 0x0015)
        /org/bluez/hci0/dev_B4_60_ED_9B_06_D2/service0001/char0002/desc0004
        00002902-0000-1000-8000-00805f9b34fb
        Client Characteristic Configuration
```

- sudo btmgt / info
```
[mgmt]# info
Index list with 1 item
hci0:   Primary controller
        addr 50:76:AF:54:40:B5 version 10 manufacturer 2 class 0x000104
        supported settings: powered connectable fast-connectable discoverable bondable link-security ssp br/edr hs le advertising secure-conn debug-keys privacy configuration static-addr
        current settings: powered ssp br/edr le secure-conn
        name mini-server
        short name
hci0:   Configuration options
        supported options: public-address
        missing options:
```

- $ sudo miauth --register "b4:60:ed:9b:06:d2"
```
Namespace(command=None, debug=False, m365=False, mac='b4:60:ed:9b:06:d2', nb=False, register=True, serial=False, token_file='./mi_token', version=False)
Using Mi
Connecting
Traceback (most recent call last):
  File "/usr/local/bin/miauth", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/miauth/cli.py", line 154, in main
    mi_main(ble)
  File "/usr/local/lib/python3.8/dist-packages/miauth/cli.py", line 103, in mi_main
    mc.connect()
  File "/usr/local/lib/python3.8/dist-packages/miauth/mi/miclient.py", line 93, in connect
    self.ble.connect()
  File "/usr/local/lib/python3.8/dist-packages/miauth/ble/blue.py", line 80, in connect
    self.p.connect(self.mac, btle.ADDR_TYPE_RANDOM)
  File "/usr/local/lib/python3.8/dist-packages/bluepy/btle.py", line 445, in connect
    self._connect(addr, addrType, iface)
  File "/usr/local/lib/python3.8/dist-packages/bluepy/btle.py", line 439, in _connect
    raise BTLEDisconnectError("Failed to connect to peripheral %s, addr type: %s" % (addr, addrType), rsp)
bluepy.btle.BTLEDisconnectError: Failed to connect to peripheral b4:60:ed:9b:06:d2, addr type: random
```

Let me know if you need any more tests

Thanks a lot

**Comment by dnandha** [comment]
Seems to be the same issue as with another device Yeelight as mentioned in #2. Yeelight products might not be compatible with `miauth`. Please look into the mentioned into, I have provided a link to an alternative project which might support the device.
